# -*- coding: utf-8 -*-
"""Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1myTMuWrZPKxTx5pdXQ1hfCLiLU9Jn9Rq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

ipums_df = pd.read_csv('/content/IPUMS.csv')
occ_df = pd.read_csv('/content/Occupation Codes.csv')

ipums_df.head() #I did this to establish how the data looked when it is read in

ipums_df.shape #I did this to verify the amount of rows and columns before any manipulation

"""#Part I: Exploratory Data Analysis and Data Preparation (Suraj and Kitiara)

#1. Handle missing or invalid values appropriately
"""

ipums_df['TELWRKPAY'] = ipums_df['TELWRKPAY'].fillna(0) #Fills the NaN in TELWRKPAY to 0 to assume the employee does not do telework

ipums_df.head() #Shows data after manipulation

"""#2. Merge the occupation code file so that occupation descriptions appear in your working dataset."""

ipums_df = pd.concat([ipums_df, occ_df], axis=1)

ipums_df.head()

"""#3. Filter the dataset in a way that makes sense for your analysis. You should clearly explain your decisions.


"""

ipums_df = ipums_df[(ipums_df['INCWAGE'] != 99999998) & (ipums_df['INCWAGE'] != 99999999)] #Filters out Missing or NIU (99999999, 99999998) for INCWAGE

ipums_df = ipums_df[(ipums_df['UHRSWORKT'] >= 0) & (ipums_df['UHRSWORKT'] <= 90)] #Filter out NIU/Unknown data for UHRSWORKT to keep values between 0 and 90

ipums_df = ipums_df[(ipums_df['UNION'] != 0) & (ipums_df['UNION'] != 1)] #Filter out NIU for UNION to filter out 0 and 1's

ipums_df = ipums_df[(ipums_df['EDUC'] != 000) & (ipums_df['EDUC'] != 999)] #Filter out NIU/Missing data for EDUC to filter out 000 and 999, taking out infants and missing records

ipums_df.shape #This shows the jump in rows after we took out all of these values

"""#4. Create the following engineered variables: HighEarner, HourlyEfficiency, EdWorkIntensity

"""

ipums_df['HighEarner'] = (ipums_df['INCWAGE'] > ipums_df['INCWAGE'].median()).astype(int)

ipums_df['HourlyEfficiency'] = ipums_df['INCWAGE'] / (ipums_df['WKSWORK1'] * ipums_df['UHRSWORKT'])

ipums_df['EdWorkIntensity'] = ipums_df['EDUC'] * ipums_df['UHRSWORKT']

ipums_df.head() #This is to show the columns were added to the df

"""#5. Identify and remove any noise variables that are not useful for your analysis. You must explain why they were removed."""

analysis_df = ipums_df.copy()

mask = occ_df['Unnamed: 3'].notna()
occ_df.loc[mask, 'Occupation Title'] = occ_df.loc[mask, 'Occupation Title'].str.strip() + ', ' + occ_df.loc[mask, 'Major Category'].str.strip()
occ_df.loc[mask, 'Major Category'] = occ_df.loc[mask, 'Unnamed: 3'].str.strip()

occ_df['OCC Code'] = occ_df['OCC Code'].replace('000N', 0)
occ_df['OCC Code'] = pd.to_numeric(occ_df['OCC Code'])

analysis_df = analysis_df.drop(columns=['OCC Code', 'Occupation Title', 'Major Category', 'Unnamed: 3'], errors='ignore')

analysis_df = pd.merge(
    analysis_df,
    occ_df[['OCC Code', 'Occupation Title', 'Major Category']],
    left_on='OCC',
    right_on='OCC Code',
    how='left'
)

analysis_df = analysis_df[(analysis_df['OCC'] != 0) & (analysis_df['WKSWORK1'] > 0) & (analysis_df['UHRSWORKT'] > 0)]

analysis_df['HourlyEfficiency'] = analysis_df['HourlyEfficiency'].replace([np.inf, -np.inf], np.nan)
analysis_df = analysis_df.dropna(subset=['HourlyEfficiency'])

analysis_df = analysis_df.drop(columns=[
    'YEAR', 'STATEFIP', 'RACE', 'MARST', 'CITIZEN',
    'IND', 'CLASSWKR', 'UNION', 'TELWRKPAY', 'OCC Code'
], errors='ignore')

analysis_df.head()

"""For this analysis, I removed all aspects unrelated to studying the workforce. I also filtered out non workforce records by removing OCC = 0 and rows with 0 weeks worked or 0 hours worked.

#6. Use groupby() to compute Avg Annual income by major, Avg hourly wage by education level, Avg hours worked by major
"""

edu_df = pd.read_excel('/content/Education.xlsx')
analysis_df = pd.merge(analysis_df, edu_df[['Value', 'Label']], left_on='EDUC', right_on='Value', how='left')

income_by_major = analysis_df.groupby('Major Category')['INCWAGE'].mean().sort_values(ascending=False)
hourly_by_education = analysis_df.groupby('Label')['HourlyEfficiency'].mean().sort_values(ascending=False)
hours_by_major = analysis_df.groupby('Major Category')['UHRSWORKT'].mean().sort_values(ascending=False)

print("Average annual income by major category")
print(income_by_major)

print("\nAverage hourly wage by education level")
print(hourly_by_education)

print("\nAverage hours worked by major category")
print(hours_by_major)

"""The grouped results here show the income changes throughout occupation categories. Higher education levels normally have higher hourly efficiency.

#7. Create at least four visualizations in the notebook (Bar, Hist, Boxplot, Line)
"""

plt.figure(figsize=(10, 6))
plt.bar(income_by_major.index, income_by_major.values)
plt.title('Average Annual Income by Major Category')
plt.xlabel('Major Category')
plt.ylabel('Average Annual Income')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""The bar chart here shows the difference between average annual income across major occupation categories. Some occupation groups such as management business and financial earn more than sales and office"""

plt.figure(figsize=(10, 6))
plt.hist(analysis_df['HourlyEfficiency'], bins=30)
plt.title('Distribution of Hourly Efficiency')
plt.xlabel('Hourly Efficiency')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

"""The histogram above shows that majority of workers are grouped in the lower range of hourly efficiency. This can explain the right skew."""

top_categories = analysis_df['Major Category'].value_counts().head(5).index
box_df = analysis_df[analysis_df['Major Category'].isin(top_categories)]

plt.figure(figsize=(10, 6))
sns.boxplot(data=box_df, x='Major Category', y='INCWAGE')
plt.title('Income Distribution for Top 5 Major Categories')
plt.xlabel('Major Category')
plt.ylabel('Annual Income')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""The boxplot above shows that income differs largely within each occupational categor. Some groups have significantly higher median incomes and a wider spread than others."""

age_income = analysis_df.groupby('AGE')['INCWAGE'].mean()

plt.figure(figsize=(10, 6))
plt.plot(age_income.index, age_income.values)
plt.title('Average Annual Income by Age')
plt.xlabel('Age')
plt.ylabel('Average Annual Income')
plt.tight_layout()
plt.show()

"""The line chart above shows the average income rising with age before leveling off later. This is because workers often earn more as they gain experience.

#Part II: Inferential Statistics (Diego and Faustina)

#1. Construct a 95% confidence interval for a mean related to income.
"""

income = ipums_df["INCWAGE"].dropna()
n = len(income)
x_bar = income.mean()
s = income.std(ddof=1)

alpha = 0.05
t_critical = stats.t.ppf(1 - alpha/2, df=n-1)

margin_of_error = t_critical * (s / np.sqrt(n))
CI = (x_bar - margin_of_error, x_bar + margin_of_error)
CI

"""Based on our sample, we estimate that the true average annual income for workers falls between $19,686,614 and 19,924,032. This 95% confidence interval means that if we repeatedly sampled similar workers and calculated a new interval each time, about 95% of those intervals would contain the true population mean.

In practical terms, the data suggests that the typical income level in this dataset is very likely somewhere within this range.
"""

ipums_df.columns

"""#2. Compare two groups of your choice that are relevant to the project."""

group1 = ipums_df[ipums_df["TELWRKPAY"] == 1]["INCWAGE"].dropna()
group2 = ipums_df[ipums_df["TELWRKPAY"] == 0]["INCWAGE"].dropna()

"""#3. Conduct a two-sample t-test"""

t_stat, p_value = stats.ttest_ind(group1, group2, equal_var=False)

print("T-statistic:", t_stat)
print("P-value:", p_value)

"""#4. Interpret the result clearly in plain language.

Conducted a two-sample t-test to compare the incomes of individuals with telework pay to those without it. The results show a p-value below 0.05, so the null hypothesis is rejected. This means the incomes are significantly different. The negative t-value suggests that the telework pay group earns less on average. However, other factors could also affect income.

#Part III: Predictive Modeling (Faustina and Suraj)

#1. Create a binary target variable:
HighEarner = 1 if AnnualIncome is greater than the median
"""

ipums_df['HighEarner'] = (ipums_df['INCWAGE'] > ipums_df['INCWAGE'].median()).astype(int)

ipums_df[['INCWAGE', 'HighEarner']].head()

"""#2. Select predictor variables that your group believes are most useful."""

X = ipums_df[['AGE', 'EDUC', 'UHRSWORKT', 'WKSWORK1', 'SEX', 'UNION', 'TELWRKPAY']]
y = ipums_df['HighEarner']

X.head()

"""#3. Train at least one classification model such as:
• Decision Tree
• Random Forest

"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X = ipums_df[['AGE', 'EDUC', 'UHRSWORKT', 'WKSWORK1', 'SEX', 'UNION', 'TELWRKPAY']]
y = ipums_df['HighEarner']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

print("Random Forest model trained successfully")

"""#4. Evaluate the model using appropriate metrics such as:
• Accuracy
• Precision
• Recall
• Confusion Matrix
"""

import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Reload df to ensure it's available if the kernel was restarted or previous cells weren't run
df = pd.read_csv('/content/IPUMS.csv')

# Assuming 'HighEarner' is created in previous cells. Re-create for robustness if df was reloaded.
df['HighEarner'] = (df['INCWAGE'] > df['INCWAGE'].median()).astype(int)

X = ipums_df[['AGE', 'EDUC', 'UHRSWORKT', 'WKSWORK1', 'SEX', 'UNION', 'TELWRKPAY']]
y = ipums_df['HighEarner']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Predictions
y_pred = rf_model.predict(X_test)

# Metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Model Performance Metrics:")
print(f"Accuracy:  {accuracy:.3f}")
print(f"Precision: {precision:.3f}")
print(f"Recall:    {recall:.3f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix Visualization
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""#5. Discuss how much you trust your model and why.

Our Random Forest model performs well overall, with an accuracy of 0.88 and high counts of correct predictions in both classes. It correctly identified 36,796 low earners and 39,487 high earners, showing that it captures the main income patterns in the dataset. The balance between true positives and true negatives suggests the model is not biased toward one group and handles both classes consistently.

However, the model still makes mistakes, including 6,416 false positives and 3,806 false negatives. These errors show that the model is reliable for general trends, but is not perfect at predicting individual outcomes. Because income depends on many factors not included in the dataset, we trust the model moderately.
It is useful for understanding patterns in earnings, but it should not be used for precise predictions.

#PART IV: Streamlit App (Kitiara and Diego)
"""

!pip install -q streamlit

!npm install localtunnel
!streamlit run app.py --server.address=localhost &>/content/logs.txt&
import urllib
print("Access the app at : ", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip('\n'))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import plotly.express as px
# 
# st.set_page_config(
#     page_title="Income Analysis Dashboard",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# x_var = st.sidebar.selectbox("X axis", ["AGE", "EDUC", "UHRSWORKT"])
# y_var = st.sidebar.selectbox("Y axis", ["INCWAGE"])
# 
# fig = px.scatter(ipums_df, x=x_var, y=y_var)
# st.plotly_chart(fig)
# 
# st.dataframe(ipums_df.head())
# 
# fig2 = px.histogram(ipums_df, x="INCWAGE")
# st.plotly_chart(fig2)